
language: c

sudo: false

before_install:
  - curl http://t2.unl.edu/store/sources/lcmaps-interface-prefix.tar.gz | tar zxv

script: ./bootstrap && ./configure --with-lcmaps-prefix=lcmaps-interface/usr/ && make

